name: PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR checklist
        uses: mheap/require-checklist-action@v5
        with:
          requireChecklist: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
